### ISSUE TITLE
isShowLogcat 方法直接崩溃

### ISSUE THREAD

**Issue by happyxiachao** [mengzhidaren/FFmpegCmdSdk#1]
java.lang.UnsatisfiedLinkError: No implementation found for void com.yyl.ffmpeg.FFmpeg.isShowLogcat(boolean) (tried Java_com_yyl_ffmpeg_FFmpeg_isShowLogcat and Java_com_yyl_ffmpeg_FFmpeg_isShowLogcat__Z)
	at com.yyl.ffmpeg.FFmpeg.isShowLogcat(Native Method)
	at com.yyl.ffmpeg.FFmpegUtils.isShowLogcat(FFmpegUtils.java:103)
	at com.yyl.demo.MainActivity.onCreate(MainActivity.java:40)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by mengzhidaren** [comment]
java.lang.UnsatisfiedLinkError   这个错误是没有对应的库文件  现在只支持arm v7a 的

**Comment by happyxiachao** [comment]
@mengzhidaren 
我现在用的就是arm v7a ，我只要把isShowLogcat（true）这个方法注释掉不调用就可以了，如果不注释掉这个方法就崩溃了，不过转码功能不受影响，目前我测过兼容安卓7.0 ，8.0还没有手机还未测试。

**Comment by mengzhidaren** [comment]
用1.0.3的版本就行了

**Comment by happyxiachao** [comment]
@mengzhidaren 
谢谢，我用的还是1.1的 已经集成到项目中了，而且进度回调也算比较及时，很多其他的项目回调没有或者跳跃很大。已经完全满足我的需求了，所以也就不需要logcat了，非常感谢你的帮助。大大的start送上！

**Comment by happyxiachao** [comment]
@mengzhidaren 可否加下你的联系方式WX或QQ 技术交流一下，你在跳跳？我们可能是同一个行业的
